import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import { PhotoIcon, UserCircleIcon } from '@heroicons/react/24/solid';
import styles from '@/styles/Home.module.css';
import { Formik, Form, Field } from 'formik';

export default function Home() {
	const handleSubmit = (values: any) => {
		saveFormData(values);
	};

	const saveFormData = (data: any) => {
		console.log(data);
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className='form-control w-full max-w-xs'>
					<Formik
						initialValues={{ name: '', email: '', phone: '' }}
						onSubmit={handleSubmit}
					>
						{({ handleChange, values }) => (
							<Form>
								<label className='label'>
									<span className='label-text'>What is your name?</span>
								</label>
								<Field
									className='input input-bordered w-full max-w-xs'
									placeholder='Type here'
									type='text'
									name='name'
									onChange={handleChange}
									value={values.name}
								/>

								<label className='label'>
									<span className='label-text'>What is your email?</span>
								</label>
								<Field
									className='input input-bordered w-full max-w-xs'
									placeholder='youremail@youremai.com'
									type='email'
									name='email'
									onChange={handleChange}
									value={values.email}
								/>

								<label className='label'>
									<span className='label-text'>What is your phone?</span>
								</label>
								<Field
									className='input input-bordered w-full max-w-xs'
									placeholder='+94112123456'
									type='tel'
									name='phone'
									onChange={handleChange}
									value={values.phone}
								/>

								<button type='submit' className='btn btn-sm'>
									Submit
								</button>
							</Form>
						)}
					</Formik>
				</div>
			</main>
		</>
	);
}
